spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/catalog
    username: postgres
    password: 12345
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_schema: catalog
  flyway:
    schemas:
      - public
      - catalog

server:
  port: 8081