spring:
  profiles:
    active: dev # По умолчанию запускается dev, но можно менять через аргументы JVM
  datasource:
    url: jdbc:postgresql://catalog-db-new:5432/catalog
    username: postgres
    password: 12345
  jpa:
    hibernate:
      ddl-auto: update  # Если временно нужно автосоздание таблицы
    properties:
      hibernate:
        default_schema: catalog
  flyway:
    schemas:
      - public
      - catalog

server:
  port: 8081